* SCRORG
A screenshot tool for Emacs' org-mode ~scrorg~. 

Imagine yourself taking notes while participating in an online
presentation and wanting to take a quick screenshot. ~scrorg~ has you
covered. ~scrorg~ leverages ~Pillow~ and ~tkinter~ to gray out the
current screen. Then use your mouse to select your area of interest,
hit RETURN and the select area will copied into an ~./img~ directory
side-by-side to your org-mode file in which you enter your notes.

* Installation
** Python-side
#+BEGIN_SRC 
pip install .
#+END_SRC
*** Requirements
#+BEGIN_SRC python
Pillow==4.2.1
#+END_SRC

** Emacs-side
In your init.el place
#+BEGIN_SRC elisp
  (defun scrorg()
    (interactive)
    (progn 
       (iconify-or-deiconify-frame)
       (let (
             (filename (substring (shell-command-to-string "scrorg") 0 -1)))
         (if (> (length filename) 0)
             (insert (format "[[file:%s]]" filename))
           (message "You escaped from scrorg.")))
       (iconify-or-deiconify-frame)))
#+END_SRC

* Usage
- From an org-file invoke 'M-x scrorg' within emacs
- The screen turns gray
- Select with your mouse your desired area
- Hit ESC to cancel the operation
- Hit RETURN to save the screenshot to directory 'img' and return to emacs inserting an image link to the just saved screenshot
- The given filename is derived from the current UTC-time.

* Tested with
- Windows 10
- Python 3.5

* License
MIT
